### ISSUE TITLE
Digital Zoom Moves Off The Screen

### ISSUE THREAD

**Issue by mylesebrown** [IBM/MicroscoPy#12]
Hello.  This project is incredible!  Thank you so much for doing the design work and making it all available here.  I have printed all of my parts with my Prusa i3 MK3S+ printer, ordered the PCB boards and soldered everything up.  I took my time and great care.  When I loaded all the software and turned it on for the first time, it worked!!  Amazing and gratifying.

That said, I have an issue I am encountering that I'd like to discuss and wonder if anyone has thoughts about how to solve this. When I zoom in with the digital zoom, the picture goes off the screen.  Is there any advice about how to solve this?  Is there a software fix that might center it?  I fear that the cause of this issue might be that the camera lens and the Raspberry Pi v2 camera are just slightly misaligned, in which case a software fix wouldn't help.  

I'll post my pictures here.  I am still learning how to position the camera and lens to achieve macro and microscopy.  I have not yet been able to create the beautiful full screen pictures that are shown in the Instruction Manual and on this GitHub
![IMG_0598](https://user-images.githubusercontent.com/74396430/107157814-1f0f1080-693b-11eb-8b69-c0770e8c1d9b.jpg)
![IMG_0597](https://user-images.githubusercontent.com/74396430/107157815-20403d80-693b-11eb-9adf-d3c18b3ab372.jpg)
![IMG_0596](https://user-images.githubusercontent.com/74396430/107157816-20d8d400-693b-11eb-80ef-c641fbc08ee0.jpg)
![IMG_0595](https://user-images.githubusercontent.com/74396430/107157823-29310f00-693b-11eb-9eae-1bed4a1c0064.jpg)
![IMG_0594](https://user-images.githubusercontent.com/74396430/107157824-2afad280-693b-11eb-8eae-0d07e430ce22.jpg)
![IMG_0593](https://user-images.githubusercontent.com/74396430/107157825-2cc49600-693b-11eb-8d9f-f5f1f0369218.jpg)
![IMG_0592](https://user-images.githubusercontent.com/74396430/107157826-2e8e5980-693b-11eb-837b-aeb69ba3a5e3.jpg)
![IMG_0591](https://user-images.githubusercontent.com/74396430/107157827-30581d00-693b-11eb-9861-c134a857d6b4.jpg)
![IMG_0590](https://user-images.githubusercontent.com/74396430/107157828-31894a00-693b-11eb-87c8-2192ab187390.jpg)
![07-02-113538](https://user-images.githubusercontent.com/74396430/107157839-3817c180-693b-11eb-9534-b82a6872171c.jpg)
![07-02-113534](https://user-images.githubusercontent.com/74396430/107157841-3948ee80-693b-11eb-9aeb-ee916a20974b.jpg)
![07-02-113526](https://user-images.githubusercontent.com/74396430/107157842-3b12b200-693b-11eb-9e7a-de25cf7b1689.jpg)
![Uploading 07-02-113521.jpg…]()

**Comment by yukseltemiz** [comment]
Hello, wow, looks great, beautiful implementation, I am very glad that you liked the project and implemented it. 

1- Yes, there is certainly an issue, I am guessing (almost certain) that maybe you forgot to remove the built-in lens of the Pi camera v2(?). Because we already have a magnifying lens, the tiny lens in front of the camera should be removed so that the lens directly projects to naked CMOS imager. Please check page 15 of the instructions pdf, it's explained at the bottom right corner, super easy, just unscrew it (I should have emphasized it better, it's a very important step). 

2- Regarding the digital zoom, when you have the microscope properly running (either the lens issue or something else), you will see that you won't even need the digital zoom, you will be amazed by the magnification level :-) But still, the digital zoom currently magnifies the top-left corner of the image, I could have centered but that would be quite some programming, I didn't have time. 

3- Just as a general comment, the respective distances between the image sensor, lens, and the sample define the magnification and the focus. For low magnification, move the camera closer to the lens, and increase the distance between the lens and the sample; for high magnification, exactly the opposite. Based on my experience, you should be able to see the whole insect in low magnification, and the individual cells in its eyes in high magnification. For high magnification, the illumination would be very important, you may also try to illuminate the sample from the top.

I hope this helps, otherwise just let me know. All the best.

**Comment by mylesebrown** [comment]
Wow! Thank you so much for your reply Yuksel!  I did indeed forget to remove the built in lens of the Pi camera.  This was exactly the problem.  The microscope is now performing beautifully!  

I have always wanted to learn about Raspberry Pi and Arduinos.  This is my first attempt.  I can't believe that nearly everything worked so perfectly on the first try except for my mistake about removing the lens.  I look forward to working more with this microscope and teaching my kids more about the technology as well as some good biology lessons.  Next, I will try to get more advanced with the lighting as you suggest.

Also, I have some ideas about upgrades/improvements that I will figure out how to post on this project page if you are ok with that?

Thank you again for sharing your talent with the world!!
Myles, 
Seattle, WA  USA

![Moth Eye High Zoom](https://user-images.githubusercontent.com/74396430/107687276-22680c00-6c5b-11eb-9606-480ab30950a7.jpg)
![Moth Antenna High Zoom](https://user-images.githubusercontent.com/74396430/107687279-2431cf80-6c5b-11eb-9a6c-3fe4f66b1738.jpg)
![Dead Moth Low Zoom](https://user-images.githubusercontent.com/74396430/107687284-2562fc80-6c5b-11eb-8286-18ecde2e8d8b.jpg)

**Comment by yukseltemiz** [comment]
This is great, thanks Myles for sharing the results and for your kind comments! I am also very impressed that you pulled everything off without much prior experience on Pi and Arduino, amazing.   

(Just one side note, you may have noticed some purple tint in the images, especially at the corners, this is because Pi camera v2 does not have an IR filter. The lens you bought probably has a filter, but it does not help much because the lens is often far from the camera in higher magnifications and the angle of incidence is not optimal, ideally the filter should be close to the camera, at least this is my interpretation... anyhow, this can be corrected by some post-processing, or I got much better results with the new HQ camera, which has a built-in IR filter: https://github.com/IBM/MicroscoPy/blob/master/HQ-camera/Instructions_HQ.pdf)

For the improvements and sharing, of course, sounds great. This was mostly a hobby project for me, and I guess we shouldn't expect too much from cheap optics but I am pretty sure there is plenty of room for improvements, this was also one of the reasons we wanted to open-source, so others can implement and improve. Looking forward to seeing your suggestions/improvements. 

Thanks, best regards,
Yuksel
